from __future__ import annotations

import asyncio
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Literal

from notification_service.providers.base import (
    Provider,
    ProviderPayload,
    ProviderResult,
)

# ── Active implementation: App Password + SMTP ────────────────────────────────
#
# Requires a Gmail App Password (not your regular Gmail password).
# Generate one at: Google Account → Security → 2-Step Verification → App passwords
#
# Required env vars:
#   GMAIL_ADDRESS       Your full Gmail address, e.g. yourname@gmail.com
#   GMAIL_APP_PASSWORD  The 16-character app password generated by Google


class GmailProvider(Provider):
    name = "gmail"

    def __init__(self) -> None:
        self._address      = os.environ.get("GMAIL_ADDRESS",      "")
        self._app_password = os.environ.get("GMAIL_APP_PASSWORD", "")

    def _send_sync(self, to: str, subject: str, body: str) -> None:
        msg = MIMEMultipart("alternative")
        msg["From"] = self._address
        msg["To"] = to
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "html"))

        with smtplib.SMTP("smtp.gmail.com", 587, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.login(self._address, self._app_password)
            server.sendmail(self._address, [to], msg.as_string())

    async def send(self, payload: ProviderPayload) -> ProviderResult:
        to = payload.recipient.email or ""
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(
            None, self._send_sync, to, payload.subject, payload.body
        )
        return ProviderResult(ok=True)

    def classify_error(self, error: Exception) -> Literal["transient", "permanent"]:
        # SMTPException is a subclass of OSError — check it before OSError
        if isinstance(error, smtplib.SMTPAuthenticationError):
            # Wrong address or app password → permanent
            return "permanent"
        if isinstance(error, smtplib.SMTPException):
            return "permanent"
        if isinstance(error, (ConnectionRefusedError, OSError, TimeoutError)):
            return "transient"
        return "permanent"


# ── Commented out: OAuth2 + Gmail REST API ────────────────────────────────────
#
# Use this instead of the App Password implementation if you have a Google Cloud
# project with the Gmail API enabled and an OAuth2 refresh token.
#
# Required env vars:
#   GMAIL_CLIENT_ID      OAuth2 client ID from Google Cloud Console
#   GMAIL_CLIENT_SECRET  OAuth2 client secret
#   GMAIL_REFRESH_TOKEN  Long-lived refresh token from the consent flow
#   GMAIL_SENDER         Sending address (must match the authenticated account)
#
# To switch back:
#   1. Comment out the App Password class above
#   2. Uncomment the OAuth2 class below
#   3. Update .env with the four OAuth2 vars instead of the two App Password vars
#
# import base64
# import httpx
# from notification_service.providers.base import classify_httpx_error
#
# _TOKEN_URL = "https://oauth2.googleapis.com/token"
# _GMAIL_SEND_URL = "https://gmail.googleapis.com/gmail/v1/users/me/messages/send"
#
#
# class GmailProvider(Provider):
#     name = "gmail"
#
#     def __init__(self) -> None:
#         self._client_id = os.environ["GMAIL_CLIENT_ID"]
#         self._client_secret = os.environ["GMAIL_CLIENT_SECRET"]
#         self._refresh_token = os.environ["GMAIL_REFRESH_TOKEN"]
#         self._sender = os.environ["GMAIL_SENDER"]
#
#     async def _get_access_token(self, client: httpx.AsyncClient) -> str:
#         resp = await client.post(
#             _TOKEN_URL,
#             data={
#                 "client_id": self._client_id,
#                 "client_secret": self._client_secret,
#                 "refresh_token": self._refresh_token,
#                 "grant_type": "refresh_token",
#             },
#         )
#         resp.raise_for_status()
#         return resp.json()["access_token"]
#
#     def _build_raw_message(self, payload: ProviderPayload) -> str:
#         msg = MIMEMultipart("alternative")
#         msg["From"] = self._sender
#         msg["To"] = payload.recipient.email or ""
#         msg["Subject"] = payload.subject
#         msg.attach(MIMEText(payload.body, "html"))
#         raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
#         return raw
#
#     async def send(self, payload: ProviderPayload) -> ProviderResult:
#         async with httpx.AsyncClient(timeout=15.0) as client:
#             token = await self._get_access_token(client)
#             raw = self._build_raw_message(payload)
#             resp = await client.post(
#                 _GMAIL_SEND_URL,
#                 headers={"Authorization": f"Bearer {token}"},
#                 json={"raw": raw},
#             )
#             resp.raise_for_status()
#             data = resp.json()
#             return ProviderResult(ok=True, message_id=data.get("id"))
#
#     def classify_error(self, error: Exception) -> Literal["transient", "permanent"]:
#         if isinstance(error, httpx.HTTPStatusError):
#             status = error.response.status_code
#             if status == 401:
#                 # invalid_grant or expired credentials → permanent
#                 return "permanent"
#             if status in (429, 500, 502, 503, 504):
#                 return "transient"
#             return "permanent"
#         return classify_httpx_error(error)
